/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RegisterIndexRouteImport } from './routes/register/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as ProtectedTodosIndexRouteImport } from './routes/_protected/todos/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ProtectedTodosNewIndexRouteImport } from './routes/_protected/todos/new/index'
import { Route as ProtectedTodosIdEditIndexRouteImport } from './routes/_protected/todos/$id/edit/index'

const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterIndexRoute = RegisterIndexRouteImport.update({
  id: '/register/',
  path: '/register/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedTodosIndexRoute = ProtectedTodosIndexRouteImport.update({
  id: '/todos/',
  path: '/todos/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedTodosNewIndexRoute = ProtectedTodosNewIndexRouteImport.update({
  id: '/todos/new/',
  path: '/todos/new/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedTodosIdEditIndexRoute =
  ProtectedTodosIdEditIndexRouteImport.update({
    id: '/todos/$id/edit/',
    path: '/todos/$id/edit/',
    getParentRoute: () => ProtectedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginIndexRoute
  '/register': typeof RegisterIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/todos': typeof ProtectedTodosIndexRoute
  '/todos/new': typeof ProtectedTodosNewIndexRoute
  '/todos/$id/edit': typeof ProtectedTodosIdEditIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginIndexRoute
  '/register': typeof RegisterIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/todos': typeof ProtectedTodosIndexRoute
  '/todos/new': typeof ProtectedTodosNewIndexRoute
  '/todos/$id/edit': typeof ProtectedTodosIdEditIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedRouteWithChildren
  '/login/': typeof LoginIndexRoute
  '/register/': typeof RegisterIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_protected/todos/': typeof ProtectedTodosIndexRoute
  '/_protected/todos/new/': typeof ProtectedTodosNewIndexRoute
  '/_protected/todos/$id/edit/': typeof ProtectedTodosIdEditIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/api/auth/$'
    | '/todos'
    | '/todos/new'
    | '/todos/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/api/auth/$'
    | '/todos'
    | '/todos/new'
    | '/todos/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/login/'
    | '/register/'
    | '/api/auth/$'
    | '/_protected/todos/'
    | '/_protected/todos/new/'
    | '/_protected/todos/$id/edit/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRoute: typeof ProtectedRouteWithChildren
  LoginIndexRoute: typeof LoginIndexRoute
  RegisterIndexRoute: typeof RegisterIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register/': {
      id: '/register/'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/todos/': {
      id: '/_protected/todos/'
      path: '/todos'
      fullPath: '/todos'
      preLoaderRoute: typeof ProtectedTodosIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/todos/new/': {
      id: '/_protected/todos/new/'
      path: '/todos/new'
      fullPath: '/todos/new'
      preLoaderRoute: typeof ProtectedTodosNewIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/todos/$id/edit/': {
      id: '/_protected/todos/$id/edit/'
      path: '/todos/$id/edit'
      fullPath: '/todos/$id/edit'
      preLoaderRoute: typeof ProtectedTodosIdEditIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
  }
}

interface ProtectedRouteChildren {
  ProtectedTodosIndexRoute: typeof ProtectedTodosIndexRoute
  ProtectedTodosNewIndexRoute: typeof ProtectedTodosNewIndexRoute
  ProtectedTodosIdEditIndexRoute: typeof ProtectedTodosIdEditIndexRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedTodosIndexRoute: ProtectedTodosIndexRoute,
  ProtectedTodosNewIndexRoute: ProtectedTodosNewIndexRoute,
  ProtectedTodosIdEditIndexRoute: ProtectedTodosIdEditIndexRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRoute: ProtectedRouteWithChildren,
  LoginIndexRoute: LoginIndexRoute,
  RegisterIndexRoute: RegisterIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
